<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoTokens\ViewModel\StoreInfoTokens;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoTokens $storeInfoTokens */
$storeInfoTokens = $viewModels->require(StoreInfoTokens::class);
?>

<?php if($storeInfoTokens->cssProps()): ?>
    <style><?= $storeInfoTokens->cssProps(); ?></style>
<?php endif; ?>
