<?php declare(strict_types=1);

/**
 * @author Siteation (https://siteation.dev/)
 * @copyright Copyright 2023 Siteation (https://siteation.dev/)
 * @license MIT
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\ThemeTokens\ViewModel\ThemeTokens;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var ThemeTokens $themeTokens */
$themeTokens = $viewModels->require(ThemeTokens::class);
?>

<?php if($themeTokens->cssProps()): ?>
    <style><?= $themeTokens->cssProps(); ?></style>
<?php endif; ?>
